/*
 * Logged.java
 *
 * Created on February 23, 2000, 4:26 PM
 */

/**
 *
 * @author  administrator
 */
import java.awt.*;
import java.io.*;
import java.util.Vector;

public class Logged extends javax.swing.JFrame {
     
    Vector v= new Vector(2);
    String sss=null;
    /** Creates new form Logged */
    public Logged() {
        initComponents();
        v.addElement(new String("Logged.java"));
        v.addElement(new String("Server.java"));
        listres.setListData(v);
               
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        listres = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        download = new javax.swing.JButton();
        save = new javax.swing.JButton();
        resArea1 = new java.awt.TextArea();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setBackground(new java.awt.Color(0, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(null);

        jPanel1.setBorder(new javax.swing.border.EtchedBorder());
        listres.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(listres);
        listres.setBounds(10, 60, 150, 130);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 15));
        jLabel1.setText("Resources Available:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 180, 40);

        download.setBackground(new java.awt.Color(204, 204, 254));
        download.setFont(new java.awt.Font("Arial", 0, 15));
        download.setText("Download..");
        download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadActionPerformed(evt);
            }
        });

        jPanel1.add(download);
        download.setBounds(170, 160, 110, 27);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 70, 340, 200);

        save.setBackground(new java.awt.Color(204, 204, 254));
        save.setFont(new java.awt.Font("Arial", 0, 15));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        getContentPane().add(save);
        save.setBounds(670, 290, 70, 27);

        getContentPane().add(resArea1);
        resArea1.setBounds(20, 290, 640, 250);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 22));
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Welcome to Honeypot Home Page");
        jLabel2.setBorder(new javax.swing.border.EtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 10, 350, 40);

        pack();
    }//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
            	try {
                        FileDialog fd=new FileDialog(this,"File Store", FileDialog.SAVE);
			fd.setVisible(true);
			String f= fd.getFile();
			fd.setFile(f); // Filename filter
			fd.setDirectory("."); // Current directory
			fd.show();
			FileOutputStream out=new FileOutputStream(f);	
			String s=resArea1.getText();
			byte b[]=s.getBytes();
			out.write(b);
		} catch(Exception e){}
    }//GEN-LAST:event_saveActionPerformed

    private void downloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadActionPerformed
        // TODO add your handling code here:
               sss=(String)listres.getSelectedValue();
               int ch=0;
		try{
			//DataInputStream  in = new DataInputStream(c.getInputStream());
                        File file = new File(sss);
                        FileInputStream in = new FileInputStream(file);
                        int i = in.available();
			char st[]=new char[i];
			int j =0;                 			
			while((ch=in.read())!=-1) {
			st[j] = (char) ch;
			j++;
			}
                        String str=new String(st);
			resArea1.setText(str);
                }catch(Exception e){ System.out.println(e); }
        
        
        
    }//GEN-LAST:event_downloadActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Logged().show();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton download;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JList listres;
    private java.awt.TextArea resArea1;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
    
}
